---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxinfo
  namespace: default
  labels:
    app: nginxinfo
  annotations:
    flux.weave.works/automated: "true"
spec:
  minReadySeconds: 5
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 60
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: nginxinfo
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        app: nginxinfo
    spec:
      imagePullSecrets:
      - name: docker-config
      containers:
      - name: nginxinfo
        image: rootk8smyexampledev.azurecr.cn/nginx:1.4
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 2000m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 64Mi
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: nginxinfo-gateway
  namespace: default
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http-nginxinfo
      protocol: HTTP
    hosts:
    - nginxinfo.myexample.dev
  - port:
      number: 443
      name: https-nginxinfo
      protocol: HTTPS
    hosts:
    - nginxinfo.myexample.dev
    tls:
      credentialName: myexample
      mode: SIMPLE
---
apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: nginxinfo
  namespace: default
spec:
  # service mesh provider (default istio)
  # can be: kubernetes, istio, appmesh, smi, nginx, gloo, supergloo
  # use the kubernetes provider for Blue/Green style deployments
  provider: istio
  # deployment reference
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginxinfo
  # the maximum time in seconds for the canary deployment
  # to make progress before it is rollback (default 600s)
  progressDeadlineSeconds: 60
  service:
    # container port
    port: 80
    # port name can be http or grpc (default http)
    portName: http
    # add all the other container ports
    # when generating ClusterIP services (default false)
    portDiscovery: false
    # Istio gateways (optional)
    gateways:
    - nginxinfo-gateway
      # remove the mesh gateway if the public host is
      # shared across multiple virtual services
    # - mesh
    # Istio virtual service host names (optional)
    hosts:
    - nginxinfo.myexample.dev
  # define the canary analysis timing and KPIs
  analysis:
    interval: 1m
    iterations: 10
    threshold: 2
    metrics:
    - name: "404s percentage"
      templateRef:
        name: not-found-percentage
        namespace: istio-system
      thresholdRange:
        max: 20
      interval: 1m
  skipAnalysis: true
