---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: podinfo-project-git
  namespace: test
spec:
  type: git
  params:
    - name: url
      value: https://github.com/skyljj/docker-sample-nginx.git
    - name: revision
      value: v1.8
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: podinfo-project-image
  namespace: test
spec:
  type: image
  params:
    - name: url
      value: rootk8smyexampledev.azurecr.cn/nginx:1.8
