---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: podinfo-project-git
  namespace: test
spec:
  type: git
  params:
    - name: url
      value: https://github.com/zembutsu/docker-sample-nginx.git
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: podinfo-project-image
  namespace: test
spec:
  type: image
  params:
    - name: url
      value: rootk8smyexampledev.azurecr.cn/nginx:latest
